# Generated by Django 3.1.6 on 2021-02-03 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0003_auto_20210203_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariomodel',
            name='usuarioApellido',
            field=models.CharField(db_column='usu_apellido', help_text='Apellido del usuario', max_length=50, verbose_name='Apellido del usuario'),
        ),
        migrations.AlterField(
            model_name='usuariomodel',
            name='usuarioNombre',
            field=models.CharField(db_column='usu_nombre', max_length=40, verbose_name='Nombre del usuario'),
        ),
        migrations.AlterField(
            model_name='usuariomodel',
            name='usuarioTipo',
            field=models.IntegerField(choices=[(1, 'ADMINISTRADOR'), (2, 'CAJERO'), (3, 'MOZO')], db_column='usu_tipo', help_text='Tipo del usuario', verbose_name='Tipo del usuario'),
        ),
    ]
