# Generated by Django 3.1.6 on 2021-02-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0004_auto_20210203_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariomodel',
            name='password',
            field=models.TextField(db_column='usu_pass', verbose_name='Contraseña del usuario'),
        ),
    ]
