# Generated by Django 3.1.6 on 2021-02-03 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventarioModel',
            fields=[
                ('inventarioId', models.AutoField(db_column='inventario_id', primary_key=True, serialize=False, unique=True)),
                ('inventarioPlato', models.CharField(db_column='inventario_plato', max_length=40, null=True, verbose_name='Nombre del Plato')),
                ('inventarioCantidad', models.IntegerField(db_column='inventario_cantidad', null=True, verbose_name='Cantidad del plato')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
                'db_table': 't_inventario',
            },
        ),
    ]
